coingecko_api_url: https://api.coingecko.com/api/v3
db_name: tomodex
env: dev
error_file: config/errors.yaml
log_level: DEBUG
run_fullnode: false
tomochain:
  exchange_address: 0x0D3ab14BBaD3D99F4203bd7a11aCB94882050E7e
  exchange_contract_address: 0x0342d186212b04E69eA682b3bed8e232b6b3361a
  lending_contract_address: 0x4d7eA2cE949216D6b120f3AA10164173615A2b6C
  http_url: http://localhost:8501
  ws_url: ws://localhost:9501
jwt_signing_key: QfCAH04Cob7b71QCqy738vw5XGSnFZ9d
jwt_verification_key: QfCAH04Cob7b71QCqy738vw5XGSnFZ9d
mongo_url: 157.245.206.12:27017
rabbitmq_url: amqp://guest:guest@localhost:5672/
server_port: 8080
simulated: false
supported_currencies: ETH,TOMO,BTC,USDT
tick_duration:
  day:
  - 1
  hour:
  - 1
  - 4
  - 12
  min:
  - 1
  - 5
  - 15
  - 30
  month:
  - 1
  - 3
  - 6
  - 9
  week:
  - 1
  year:
  - 1
